name: Jamie Esterman
favicon: null
layout_spectrum: 0.5673759612254798
typography_spectrum: 0.7131813077721745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.10624149884097278
  lightness: 0.37051722640171647
  saturation: 0.43041637167334557
  rhythmicContrast: 0.8877211371436715
purpose: []
